_target_: src.models.tpp_module.TPPLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.0001
  weight_decay: 0.0001
  eps: 1e-05
  betas: [0.9, 0.999]

net:
  _target_: src.models.tpp.tpp_network.IntensityFreePredictor
  name: 'if'
  hidden_dim: 96
  num_components: 8
  num_classes: ${data.datasets.num_classes}
  activation:
    name: tanh
    in_features: ${model.net.hidden_dim}
